### ISSUE TITLE
Segmentation is different in 64-bit mode

### ISSUE THREAD

**Issue by phil-opp** [gz/rust-x86#26]
In 64-bit mode, segmentation is no longer supported. The GDT and segment selectors still exist, but there are great differences:

- no base/limit fields
- no privilege checking (DPL and RPL are irgnored)
- most other bits are ignored, too (e.g. accessed, read/write, etc)
- some descriptors are 16 bytes (instead of the default 8 bytes): see #25 

Therefore we should move most of the segmentation module to `bits32` and create new 64-bit types.

I would be happy to submit a PR if you're interested.

**Comment by gz** [comment]
Yeah thanks for reporting this. It seems this happened due to the merge with the libcpu library (the 0.8.0 version of SegementDescriptor was more x86-64ish https://github.com/gz/rust-x86/blob/a2cc4e66539f8dd47e3a5b0245a0927728603462/src/segmentation.rs)

I'm happy to have seperate types for this as segmentation is essentially disabled anyways. If you have time to submit a pull request, that would be great.

**Comment by ColinFinck** [comment]
Fixed by PR #32
